### PR TITLE
Document actual 690 usage from InspIRCd

### PR DESCRIPTION
**Pull request by jwheare**
I just chose the ERR_REDIRECT name myself, insp doesn't use a named constant and that one was unused and seemed consistent.

### CODE REVIEW

**Comment by jwheare** [comment]
Don't merge, spotted an issue in the preview.

**Comment by jwheare** [comment]
Ok fixed. squash it for the love of god

**Comment by jwheare** [comment]
and don't preserve the sub commit descs!

**Comment by DanielOaks** [comment]
Thanks as always mate <3

**Pull request merged**
