### PR TITLE
add conflicted TLS modes

### PR DESCRIPTION
**Pull request by slingamn**
based on findings from https://github.com/ircv3/ircv3-ideas/issues/45

### CODE REVIEW

**Comment by jwheare** [comment]
Ace! Maybe add e.g. “See also +S 	SECURED_ONLY“ in the description for +z 	SECURED_ONLY in chan modes. And vice versa and similar in all user/chan modes that share a behaviour but not a letter.

**Comment by jwheare** [comment]
Do the names (eg SSLQUERIES) all come from constants in source code? Can they be normalised or is the distinction helpful?

**Comment by jwheare** [comment]
LGTM :shipit:

**Comment by edk0** [comment]
+Z for TLS is from charybdis

**Comment by DanielOaks** [comment]
I'll merge for now and note that Chary thing. We have some CI stuff to sort out but can always do it a little later, thanks for the changes!

**Pull request merged**
